name: ci

on:
  push:
    paths:
    - "action.yml"
    - "Dockerfile"
    - "entrypoint.sh"
    - ".github/workflows/ci.yml"

env:
  STACK_NAME: 'test-stack'

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - name: clone the repo
        uses: actions/checkout@v3
      - name: test cfn-check-status
        uses: ./
        id: ccs
        with:
          cfn-stack-name: env.STACK_NAME
