name: release

on:
 push:
   tags:
     - "v*"

jobs:
  release:
    name: release cfn-check-failed-status
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/release-github-actions@v6
